extends: spectral:oas
functions: [x-header-parameter]
rules:
  wrong-version:
    description: OpenApi version must be 3.x.x
    given: $.openapi
    severity: error
    then:
      field: "@value"
      function: pattern
      functionOptions:
        match: "^3\.\d\.\d+$"
  x-header-not-set:
    message: "{{error}}"
    given: $.paths.*.post
    severity: error
    then:
      function: "x-header-parameter"
      functionOptions:
        value: "test"