language: java
jdk:
  - openjdk8

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - echo "<settings><servers><server><id>github</id><username>\${env.CI_DEPLOY_USERNAME}</username><password>\${env.CI_DEPLOY_PASSWORD}</password></server></servers></settings>" > settings.xml
  - mvn deploy --settings settings.xml