resourcePackages:
- ch.baloise.corellia.api
prettyPrint: true
cacheTTL: 0
openAPI:
  info:
    version: '0.0.1'
    title: 'Contracts API'
    description: 'An API which allows to communicate with SaaS Providers, which produces Contracts for the host of this API'
    contact:
      email: Group.CH_Open-Source@baloise.ch
    license:
      name: Apache License 2.0
      url: https://github.com/baloise/corellia/blob/master/LICENSE.txt
