resourcePackages:
- ch.baloise.corellia.api
prettyPrint: true
cacheTTL: 0
openAPI:
  info:
    version: '1.0.0'
    title: 'Contracts API'
    description: 'An API which allows to communicate with SaaS Providers, which produces Contracts for the host of this API'
    contact:
      email: TBD.TBD@baloise.com
    license:
      name: TBD
      url: TBD